"MD007": false # list indent; https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md007.md
# pymarkdown requires 4 space indent for nested lists; markdownlint and prettier have mutually-exclusive
# opinions (and prettier is intentionally not configurable)

"MD013": false # Line length; https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md013.md
"MD033": false # Inline HTML; https://github.com/DavidAnson/markdownlint/blob/v0.29.0/doc/md033.md
