# See https://squidfunk.github.io/mkdocs-material/
# https://www.mkdocs.org/user-guide/deploying-your-docs/#organization-and-user-pages
# https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

site_name: "HGVS Nomenclature"
site_url: https://hgvs-nomenclature.org/
strict: true

plugins:
- awesome-pages
- markdown-exec
- search
- table-reader
- macros # must be after table-reader

markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- markdown_captions
- pymdownx.details
- pymdownx.superfences
- toc:
    permalink: "#"
    toc_depth: 1

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/HGVSNomenclature/hgvs-nomenclature

extra_css:
- stylesheets/extra.css

theme:
  name: material
  #custom_dir: overrides

  features:
  - navigation.indexes
  - navigation.instant
  - navigation.tracking
  - search.highlight
  - toc.follow
  - toc.integrate

  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: hvnc
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  font:
    text: Ubuntu
    code: Roboto Mono
  logo: images/hgvs-logo.png
  favicon: images/hgvs-logo.png

watch:
- bin
- lib
- overrides
- overrides/partials
