# See https://squidfunk.github.io/mkdocs-material/
# https://www.mkdocs.org/user-guide/deploying-your-docs/#organization-and-user-pages
# https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins

site_name: "HGVS Nomenclature"
site_url: https://hgvs-nomenclature.org
repo_url: https://github.com/HGVSNomenclature/hgvs-nomenclature
# strict: true

plugins:
  - awesome-pages
  - markdown-exec
  - search
  - table-reader
  - macros # must be after table-reader

hooks:
  - hooks.py

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - markdown_captions
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
      toc_depth: 1

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HGVSNomenclature/hgvs-nomenclature

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides

  features:
    - announce.dismiss
    - navigation.indexes # enable section-level pages
    - navigation.instant # single-page app
    - navigation.tracking # add section fragment to URL
    - search.highlight # highlight search terms in pages
    - toc.follow # toc follows scroll
    - toc.integrate # integrate page headings into toc
  # Tabs are nice, but apparently remove the side nav
  # - navigation.tabs
  # - navigation.tabs.sticky

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: hvnc
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Lato
    code: Roboto Mono
  logo: images/hgvs-logo.png
  favicon: images/hgvs-logo.png

watch:
  - bin
  - lib
  - overrides
  - overrides/partials
  - hooks.py
